set_property IOSTANDARD LVCMOS33 [get_ports data_out_ready]
set_property IOSTANDARD LVCMOS33 [get_ports data_out]
set_property IOSTANDARD LVCMOS18 [get_ports data]
set_property IOSTANDARD LVCMOS18 [get_ports data_in_enable]
set_property IOSTANDARD LVCMOS18 [get_ports data_out_query]
set_property IOSTANDARD LVCMOS18 [get_ports load_clk]
set_property IOSTANDARD LVCMOS18 [get_ports clk]
set_property PACKAGE_PIN H17 [get_ports data]
set_property PACKAGE_PIN M15 [get_ports data_in_enable]
set_property PACKAGE_PIN H18 [get_ports data_out_query]
set_property PACKAGE_PIN H19 [get_ports load_clk]
set_property PACKAGE_PIN U14 [get_ports data_out]
set_property PACKAGE_PIN U19 [get_ports data_out_ready]
set_property PACKAGE_PIN Y9 [get_ports clk]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets data_out_query_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets load_clk_IBUF]

create_clock -period 10.000 -name clk100 -waveform {0.000 5.000} [get_ports clk]
